# Generated by Django 5.2.7 on 2025-10-30 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_comfirmed',
            field=models.BooleanField(default=False),
        ),
    ]
